version: "3"
services:
    redis:
        image: "redis:latest"
    node-app:
        restart: always
        build: .
        ports:
            - "3200:8082"
        depends_on:
            - redis

